### ISSUE TITLE
请问能分享一下训练出的预训练权重吗

### ISSUE THREAD

**Issue by SDGLBL** [Jinglever/baidu-lane-detection-2019#1]
如题

**Comment by Jinglever** [comment]
点下面的链接下载哈，提取码是：yca3
https://pan.baidu.com/s/1eF3FWzItdiFIKN2DvlAzog

**Comment by zz-howard** [comment]
> 如题

点下面的链接下载哈，提取码是：yca3
https://pan.baidu.com/s/1eF3FWzItdiFIKN2DvlAzog

**Comment by zz-howard** [comment]
补充一下，上面的权重对应的参数是：
IMAGE_SIZE = (1536, 512)

**Comment by SDGLBL** [comment]
> 补充一下，上面的权重对应的参数是：
> IMAGE_SIZE = (1536, 512)

谢谢
