### ISSUE TITLE
关于pytorch的版本

### ISSUE THREAD

**Issue by cbhxdyx** [Jinglever/baidu-lane-detection-2019#5]
可以问下torch的版本吗?还有就是每个尺寸的训练epoch数.因为我看代码里面好像是总共的epoch是30轮.但是并没有说明每个尺寸的epoch.我想复现一下结果,所以不知道您可以告知一下吗?

**Comment by zz-howard** [comment]
> 可以问下torch的版本吗?还有就是每个尺寸的训练epoch数.因为我看代码里面好像是总共的epoch是30轮.但是并没有说明每个尺寸的epoch.我想复现一下结果,所以不知道您可以告知一下吗?

应该是torch 1.6版。每个尺寸的epoch数应该都是30轮哈。有点儿久，记不太清楚了。

**Comment by cbhxdyx** [comment]
多谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jinglever/baidu-lane-detection-2019"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月12日(星期二) 中午1:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jinglever/baidu-lane-detection-2019] 关于pytorch的版本 (#5)





  
可以问下torch的版本吗?还有就是每个尺寸的训练epoch数.因为我看代码里面好像是总共的epoch是30轮.但是并没有说明每个尺寸的epoch.我想复现一下结果,所以不知道您可以告知一下吗?
  
应该是torch 1.6版。每个尺寸的epoch数应该都是30轮哈。有点儿久，记不太清楚了。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
